import { VisaDecisionTree } from "./model";

export const turkeyVisaDecisionTree: VisaDecisionTree = {
  startQuestionId: "q1",
  questions: {
    q1: {
      id: "q1",
      text: "What is the main purpose of your visit to Turkey?",
      answerType: "single",
      options: [
        { id: "a1", text: "Tourism/Visit", nextQuestionId: "q2" },
        { id: "a2", text: "Work", nextQuestionId: "q3" },
        { id: "a3", text: "Study", nextQuestionId: "q4" },
        { id: "a4", text: "Family Reunification", nextQuestionId: "q5" },
        { id: "a5", text: "Long-term Residence/Retirement", nextQuestionId: "q6" },
        { id: "a6", text: "Transit through Turkey", nextQuestionId: "q7" },
        { id: "a7", text: "Business/Conference", nextQuestionId: "q8" },
        { id: "a8", text: "Property Ownership", nextQuestionId: "q9" },
      ],
      helpText: "Select the main reason for your travel to Turkey",
    },

    q2: {
      id: "q2",
      text: "How long do you plan to stay in Turkey for tourism?",
      answerType: "single",
      options: [
        { id: "a1", text: "Less than 90 days", nextQuestionId: "q10" },
        { id: "a2", text: "More than 90 days", nextQuestionId: "r2" },
      ],
      helpText: "Most tourist visas allow stays of up to 90 days within a 180-day period",
    },

    q3: {
      id: "q3",
      text: "What type of work will you be doing in Turkey?",
      answerType: "single",
      options: [
        { id: "a1", text: "Employment with a Turkish company", nextQuestionId: "r3" },
        { id: "a2", text: "Self-employment/Freelance work", nextQuestionId: "r4" },
        { id: "a3", text: "Digital nomad/Remote work for non-Turkish employer", nextQuestionId: "r5" },
        { id: "a4", text: "Internship", nextQuestionId: "r6" },
        { id: "a5", text: "Teaching/Educational position", nextQuestionId: "r7" },
      ],
      helpText: "Different types of work in Turkey require different permits",
    },

    q4: {
      id: "q4",
      text: "What is the duration of your study program in Turkey?",
      answerType: "single",
      options: [
        { id: "a1", text: "Less than a month (short course/language program)", nextQuestionId: "q10" },
        { id: "a2", text: "1-3 months (summer school/certificate program)", nextQuestionId: "q10" },
        { id: "a3", text: "More than 3 months (semester/full degree program)", nextQuestionId: "r8" },
      ],
      helpText: "Longer study programs require student residence permits",
    },

    q5: {
      id: "q5",
      text: "What is your relationship with the person in Turkey?",
      answerType: "single",
      options: [
        { id: "a1", text: "Spouse of a Turkish citizen", nextQuestionId: "r9" },
        { id: "a2", text: "Spouse of a foreign resident in Turkey", nextQuestionId: "r10" },
        { id: "a3", text: "Child of a Turkish citizen or resident", nextQuestionId: "r11" },
        { id: "a4", text: "Parent of a Turkish citizen or resident", nextQuestionId: "r12" },
        { id: "a5", text: "Other family relationship", nextQuestionId: "r13" },
      ],
      helpText: "Family relationships determine eligibility for family residence permits",
    },

    q6: {
      id: "q6",
      text: "What type of long-term residence are you interested in?",
      answerType: "single",
      options: [
        { id: "a1", text: "Retirement (for pensioners/retirees)", nextQuestionId: "r14" },
        { id: "a2", text: "Long-term residence without working", nextQuestionId: "r15" },
        { id: "a3", text: "Residence based on property ownership", nextQuestionId: "r16" },
        { id: "a4", text: "Turkish Citizenship through investment", nextQuestionId: "r17" },
      ],
      helpText: "Turkey offers various long-term residence options based on different circumstances",
    },

    q7: {
      id: "q7",
      text: "How long will you be transiting through Turkey?",
      answerType: "single",
      options: [
        { id: "a1", text: "Less than 24 hours, staying in airport transit zone", nextQuestionId: "r18" },
        { id: "a2", text: "Will leave airport/Need to stay overnight before connecting flight", nextQuestionId: "q10" },
      ],
      helpText: "If you need to leave the airport transit area, you may need a visa or e-Visa",
    },

    q8: {
      id: "q8",
      text: "How long will your business visit to Turkey last?",
      answerType: "single",
      options: [
        { id: "a1", text: "Less than 90 days (meetings, conferences, etc.)", nextQuestionId: "q10" },
        { id: "a2", text: "More than 90 days", nextQuestionId: "r19" },
      ],
      helpText: "Short business trips can usually use tourist visas, longer stays may require work permits",
    },

    q9: {
      id: "q9",
      text: "Are you planning to purchase property in Turkey?",
      answerType: "single",
      options: [
        { id: "a1", text: "Yes, with value of $400,000 USD or more", nextQuestionId: "r20" },
        { id: "a2", text: "Yes, but less than $400,000 USD", nextQuestionId: "r21" },
        { id: "a3", text: "No, just exploring options", nextQuestionId: "q10" },
      ],
      helpText: "Property purchases above certain values may qualify for residence permits or citizenship",
    },

    q10: {
      id: "q10",
      text: "What is your citizenship?",
      answerType: "single",
      options: [
        { id: "a1", text: "Visa-exempt country (Most EU countries, UK, etc.)", nextQuestionId: "r1" },
        { id: "a2", text: "E-Visa eligible country (USA, Canada, Australia, etc.)", nextQuestionId: "r22" },
        { id: "a3", text: "Visa-required country", nextQuestionId: "r23" },
        { id: "a4", text: "Not sure if I need a visa", nextQuestionId: "r24" },
      ],
      helpText: "Your citizenship determines if you need a visa and what type",
    },
  },

  results: {
    r1: {
      id: "r1",
      title: "Visa-Free Entry",
      description: "Citizens of certain countries can enter Turkey without a visa for short stays.",
      requirements: [
        "Valid passport with at least 6 months validity beyond your entry date",
        "Return ticket or proof of onward travel",
        "Proof of accommodation for your stay",
        "Sufficient funds for your stay (may be asked to demonstrate this)",
        "Maximum stay of 90 days within any 180-day period",
      ],
      applicationLinks: [
        {
          text: "Official Republic of Turkey Ministry of Foreign Affairs Visa Information",
          url: "http://www.mfa.gov.tr/visa-information-for-foreigners.en.mfa",
        },
      ],
      processingTime: "No processing time - entry permitted at border",
      cost: {
        amount: 0,
        currency: "USD",
      },
      alternativeOptions: ["r22", "r2"],
      applicableCountries: [
        "Albania",
        "Andorra",
        "Argentina",
        "Belize",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Brazil",
        "Bulgaria",
        "Chile",
        "Colombia",
        "Czech Republic",
        "Denmark",
        "Ecuador",
        "El Salvador",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Guatemala",
        "Holy See (Vatican)",
        "Honduras",
        "Hong Kong (BNO)",
        "Hungary",
        "Iceland",
        "Italy",
        "Japan",
        "Kosovo",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Malaysia",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "North Macedonia",
        "Panama",
        "Paraguay",
        "Peru",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Serbia",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "South Korea",
        "Spain",
        "Sweden",
        "Switzerland",
        "Thailand",
        "Ukraine",
        "United Kingdom",
        "Uruguay",
        "Venezuela",
      ],
    },

    r2: {
      id: "r2",
      title: "Tourist Residence Permit",
      description: "For tourists who want to stay in Turkey for longer than 90 days.",
      requirements: [
        "Valid passport with at least 60 days validity beyond the requested permit duration",
        "Application must be made before your visa/visa-free stay expires",
        "Health insurance covering your stay in Turkey",
        "Proof of sufficient funds to support yourself (bank statements)",
        "Proof of accommodation/address in Turkey",
        "Four biometric photos",
        "Application fee payment receipt",
        "Application must be made via the e-ikamet system and completed in person at the Immigration Office",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and permit duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r15", "r22"],
      applicableCountries: ["All countries"],
    },

    r3: {
      id: "r3",
      title: "Work Permit for Employment",
      description: "Required for foreigners who want to work for a Turkish employer in Turkey.",
      requirements: [
        "Valid passport",
        "Employment contract or job offer from a Turkish company",
        "The employer must apply on your behalf through the Ministry of Family, Labor and Social Services",
        "Company must meet certain criteria (capital, number of Turkish employees, etc.)",
        "Application should be made while you are outside Turkey (in most cases)",
        "University degree or qualification relevant to the position",
        "Health insurance",
        "Work permit also serves as your residence permit",
      ],
      applicationLinks: [
        {
          text: "Ministry of Family, Labor and Social Services Work Permit Application",
          url: "https://www.calismaizni.gov.tr/en/",
        },
      ],
      processingTime: "30-90 days",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r4", "r5"],
      applicableCountries: ["All countries"],
    },

    r4: {
      id: "r4",
      title: "Self-Employed Work Permit",
      description: "For foreigners who want to establish a business or work as self-employed in Turkey.",
      requirements: [
        "Valid passport",
        "Establishment of a company in Turkey or registration as a self-employed professional",
        "Business plan and proof of sufficient capital",
        "Trade registry documents and tax registration",
        "Must have been residing in Turkey legally for at least 6 months (in most cases)",
        "Application via e-Devlet system or through the Ministry of Family, Labor and Social Services",
        "Evidence of qualification/expertise in your field",
        "Health insurance",
      ],
      applicationLinks: [
        {
          text: "Ministry of Family, Labor and Social Services Self-Employment Information",
          url: "https://www.calismaizni.gov.tr/en/",
        },
      ],
      processingTime: "60-120 days",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r3", "r19"],
      applicableCountries: ["All countries"],
    },

    r5: {
      id: "r5",
      title: "Digital Nomad/Remote Worker Options",
      description: "For those who work remotely for employers outside Turkey while staying in Turkey.",
      requirements: [
        "Turkey does not have a specific digital nomad visa yet",
        "Options include:",
        "• Using tourist visa/e-Visa for stays up to 90 days",
        "• Applying for a tourist residence permit for longer stays",
        "• Not legally permitted to work for Turkish companies without a work permit",
        "Valid passport",
        "Proof of income from foreign sources",
        "Health insurance",
        "For longer stays: apply for tourist residence permit via e-ikamet system",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System (for longer stays)",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "Varies based on chosen option",
      cost: {
        amount: 0,
        currency: "USD/TRY (depends on visa/permit type)",
      },
      alternativeOptions: ["r2", "r15"],
      applicableCountries: ["All countries"],
    },

    r6: {
      id: "r6",
      title: "Internship Permission",
      description: "For international students wanting to complete an internship in Turkey.",
      requirements: [
        "Acceptance letter from a Turkish company/institution for internship",
        "Must be part of a formal education program in most cases",
        "Letter from your university/educational institution confirming the internship requirement",
        "If internship is unpaid and less than 90 days: tourist visa may be sufficient",
        "For paid internships or longer than 90 days: work permit application required",
        "Work permit application must be made by the hosting Turkish company",
        "Health insurance covering your stay in Turkey",
      ],
      applicationLinks: [
        {
          text: "Ministry of Family, Labor and Social Services",
          url: "https://www.calismaizni.gov.tr/en/",
        },
      ],
      processingTime: "30-60 days for work permit if required",
      cost: {
        amount: 0,
        currency: "TRY (varies based on duration and type of permission)",
      },
      alternativeOptions: ["r3", "r8"],
      applicableCountries: ["All countries"],
    },

    r7: {
      id: "r7",
      title: "Teaching/Academic Work Permit",
      description: "For foreign educators, teachers, and academics working in Turkish educational institutions.",
      requirements: [
        "Job offer from a Turkish educational institution",
        "University degree and teaching credentials",
        "For university positions: relevant academic qualifications (Ph.D. often required)",
        "Work permit application must be submitted by the educational institution",
        "Ministry of Education or YÖK (Higher Education Council) approval",
        "Health insurance",
        "Criminal record check may be required",
        "Work permit also serves as residence permit",
      ],
      applicationLinks: [
        {
          text: "Ministry of Family, Labor and Social Services - Foreign Teachers",
          url: "https://www.calismaizni.gov.tr/en/",
        },
      ],
      processingTime: "30-90 days",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r3", "r8"],
      applicableCountries: ["All countries"],
    },

    r8: {
      id: "r8",
      title: "Student Residence Permit",
      description: "For international students enrolled in Turkish educational institutions.",
      requirements: [
        "Acceptance letter from a Turkish educational institution",
        "Valid passport with at least 60 days validity beyond the requested permit duration",
        "Apply via the e-ikamet system before your visa expires",
        "Proof of enrollment and payment of tuition fees",
        "Proof of sufficient funds to support yourself during studies",
        "Health insurance covering your stay in Turkey",
        "Proof of accommodation in Turkey",
        "Four biometric photos",
        "Students may work part-time after obtaining work permission (limited hours)",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r2", "r22"],
      applicableCountries: ["All countries"],
    },

    r9: {
      id: "r9",
      title: "Family Residence Permit (Spouse of Turkish Citizen)",
      description: "For foreign spouses of Turkish citizens.",
      requirements: [
        "Valid marriage certificate (must be registered with Turkish authorities)",
        "Valid passport",
        "Application via e-ikamet system",
        "Turkish spouse must provide proof of Turkish citizenship",
        "Proof of joint residence in Turkey",
        "Health insurance (unless covered by Turkish spouse's insurance)",
        "Four biometric photos",
        "Initial permit typically issued for 2 years, can be renewed",
        "After 3 years of marriage, may apply for Turkish citizenship",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality, paid in Turkish Lira)",
      },
      alternativeOptions: ["r10", "r17"],
      applicableCountries: ["All countries"],
    },

    r10: {
      id: "r10",
      title: "Family Residence Permit (Spouse of Foreign Resident)",
      description: "For foreign spouses of foreigners legally residing in Turkey.",
      requirements: [
        "Valid marriage certificate (apostilled/legalized)",
        "Spouse must have legal residence permit in Turkey",
        "Valid passport with at least 60 days validity beyond the requested permit duration",
        "Application via e-ikamet system",
        "Proof of joint residence in Turkey",
        "Health insurance",
        "Spouse must demonstrate sufficient financial resources",
        "Four biometric photos",
        "Duration normally cannot exceed spouse's permit duration",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r9", "r2"],
      applicableCountries: ["All countries"],
    },

    r11: {
      id: "r11",
      title: "Family Residence Permit (Child)",
      description: "For minor children of Turkish citizens or legal residents in Turkey.",
      requirements: [
        "Birth certificate proving relationship (apostilled/legalized)",
        "Valid passport for the child",
        "Parent(s) must have Turkish citizenship or valid residence permits",
        "Application via e-ikamet system",
        "Health insurance",
        "Four biometric photos of child",
        "For children under 18, application must be made by parent/legal guardian",
        "For children of Turkish citizens, may be eligible for Turkish citizenship",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r13", "r17"],
      applicableCountries: ["All countries"],
    },

    r12: {
      id: "r12",
      title: "Family Residence Permit (Parent)",
      description: "For dependent parents of Turkish citizens or legal residents in Turkey.",
      requirements: [
        "Documentation proving family relationship",
        "Valid passport",
        "Application via e-ikamet system",
        "Proof of dependency (financial, medical, etc.)",
        "Child in Turkey must demonstrate sufficient financial resources",
        "Health insurance",
        "Four biometric photos",
        "May require additional documentation proving need for care",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r13", "r14"],
      applicableCountries: ["All countries"],
    },

    r13: {
      id: "r13",
      title: "Other Family Residence Permits",
      description: "For other family members of Turkish citizens or legal residents not covered by standard categories.",
      requirements: [
        "Documentation proving family relationship",
        "Valid passport",
        "Application via e-ikamet system",
        "Proof of dependency in many cases",
        "Family member in Turkey must demonstrate sufficient financial resources",
        "Health insurance",
        "Proof of accommodation in Turkey",
        "Four biometric photos",
        "Cases evaluated individually based on circumstances",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province and complexity",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r2", "r15"],
      applicableCountries: ["All countries"],
    },

    r14: {
      id: "r14",
      title: "Retirement Residence Permit",
      description: "For retirees and pensioners who want to live in Turkey without working.",
      requirements: [
        "Valid passport",
        "Proof of retirement status from home country",
        "Proof of regular pension or retirement income",
        "Application via e-ikamet system",
        "Health insurance valid in Turkey",
        "Proof of accommodation in Turkey",
        "Four biometric photos",
        "Bank statements showing sufficient funds for living expenses",
        "No intention to work in Turkey",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r15", "r16"],
      applicableCountries: ["All countries"],
    },

    r15: {
      id: "r15",
      title: "Short-term Residence Permit",
      description: "General residence permit for various purposes not covered by specific categories.",
      requirements: [
        "Valid passport with at least 60 days validity beyond the requested permit duration",
        "Application via e-ikamet system",
        "Proof of sufficient financial resources",
        "Health insurance valid in Turkey",
        "Proof of accommodation in Turkey",
        "Four biometric photos",
        "May need to provide reason for stay (property ownership, treatment, etc.)",
        "Does not allow employment without separate work permit",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r2", "r16"],
      applicableCountries: ["All countries"],
    },

    r16: {
      id: "r16",
      title: "Property Owner Residence Permit",
      description: "For foreigners who own property in Turkey.",
      requirements: [
        "Proof of property ownership (title deed/TAPU)",
        "Valid passport",
        "Application via e-ikamet system",
        "Health insurance valid in Turkey",
        "Four biometric photos",
        "Property must be registered in applicant's name",
        "Initial permit typically for 1-2 years, renewable",
        "Does not allow employment without separate work permit",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r15", "r17"],
      applicableCountries: ["All countries where foreign property ownership is permitted"],
    },

    r17: {
      id: "r17",
      title: "Turkish Citizenship by Investment",
      description: "Program allowing foreign investors to obtain Turkish citizenship through qualifying investments.",
      requirements: [
        "Purchase real estate worth at least $400,000 USD with commitment not to sell for 3 years",
        "OR make a capital investment of at least $500,000 USD",
        "OR create jobs for at least 50 people",
        "OR deposit at least $500,000 USD in Turkish banks for 3 years",
        "OR purchase government bonds worth at least $500,000 USD for 3 years",
        "Obtain a short-term residence permit first",
        "Apply for Turkish citizenship through the exceptional citizenship program",
        "Security background check",
        "Health insurance",
      ],
      applicationLinks: [
        {
          text: "Turkish Citizenship by Investment Program",
          url: "https://www.invest.gov.tr/en/investmentguide/Pages/acquiring-turkish-citizenship.aspx",
        },
      ],
      processingTime: "3-6 months after qualifying investment is made",
      cost: {
        amount: 400000,
        currency: "USD (minimum investment amount, plus application fees)",
      },
      alternativeOptions: ["r16", "r15"],
      applicableCountries: ["All countries"],
    },

    r18: {
      id: "r18",
      title: "Airport Transit Information",
      description: "Requirements for transit passengers who will not leave the international transit area of Turkish airports.",
      requirements: [
        "Valid passport",
        "Confirmed onward ticket for departure within 24 hours",
        "May need an airport transit visa depending on citizenship",
        "Meeting entry requirements for your final destination",
        "Transit visa not required for many nationalities if staying in the international transit area",
        "If you need to leave the transit area or stay overnight, regular visa rules apply",
      ],
      applicationLinks: [
        {
          text: "Turkish Ministry of Foreign Affairs Visa Information",
          url: "http://www.mfa.gov.tr/visa-information-for-foreigners.en.mfa",
        },
      ],
      processingTime: "Varies by visa type if required",
      cost: {
        amount: 0,
        currency: "USD (free for transit without visa, regular visa fees apply if visa needed)",
      },
      alternativeOptions: ["r22", "r23"],
      applicableCountries: ["All countries"],
    },

    r19: {
      id: "r19",
      title: "Business Residence Permit",
      description: "For business people who need to stay in Turkey longer than 90 days for business activities.",
      requirements: [
        "Valid passport",
        "Application via e-ikamet system",
        "Documentation regarding business activities in Turkey",
        "May include letters from Turkish business partners/companies",
        "Company registration documents if applicable",
        "Proof of sufficient financial resources",
        "Health insurance valid in Turkey",
        "Four biometric photos",
        "Note: For actual employment, a work permit is required",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r3", "r4"],
      applicableCountries: ["All countries"],
    },

    r20: {
      id: "r20",
      title: "Real Estate Investment for Citizenship",
      description: "Information for those purchasing property valued at $400,000 USD or more to qualify for Turkish citizenship.",
      requirements: [
        "Purchase property worth at least $400,000 USD",
        "Property valuation must be confirmed by authorized institutions",
        "Title deed must include annotation that property cannot be sold for 3 years",
        "Obtain short-term residence permit",
        "Apply for Turkish citizenship through exceptional citizenship program",
        "Security background check",
        "Health report from authorized Turkish hospital",
        "Process typically handled through specialized law firms",
      ],
      applicationLinks: [
        {
          text: "Turkish Citizenship by Investment Program",
          url: "https://www.invest.gov.tr/en/investmentguide/Pages/acquiring-turkish-citizenship.aspx",
        },
      ],
      processingTime: "3-6 months after property purchase is completed",
      cost: {
        amount: 400000,
        currency: "USD (minimum investment amount, plus legal fees and application costs)",
      },
      alternativeOptions: ["r17", "r16"],
      applicableCountries: ["All countries where foreign property ownership is permitted"],
    },

    r21: {
      id: "r21",
      title: "Property Ownership Residence Permit",
      description: "For foreigners purchasing property in Turkey valued at less than $400,000 USD.",
      requirements: [
        "Valid property title deed (TAPU) in your name",
        "Valid passport",
        "Application via e-ikamet system",
        "Health insurance valid in Turkey",
        "Four biometric photos",
        "Property ownership allows application for residence permit",
        "Initial permit typically for 1-2 years, renewable",
        "Not eligible for citizenship through investment program",
      ],
      applicationLinks: [
        {
          text: "e-Residence Permit Application System",
          url: "https://e-ikamet.goc.gov.tr/",
        },
      ],
      processingTime: "2-8 weeks depending on the province",
      cost: {
        amount: 0,
        currency: "TRY (fees vary by nationality and duration, paid in Turkish Lira)",
      },
      alternativeOptions: ["r16", "r15"],
      applicableCountries: ["All countries where foreign property ownership is permitted"],
    },

    r22: {
      id: "r22",
      title: "Electronic Visa (e-Visa)",
      description: "Online visa application system for eligible nationalities visiting Turkey for tourism or business.",
      requirements: [
        "Valid passport with at least 6 months validity beyond entry date",
        "Apply online through official e-Visa portal",
        "Payment by credit/debit card",
        "Intended stay of maximum 90 days (may vary by nationality)",
        "Return ticket or proof of onward travel may be required",
        "Sufficient funds for your stay",
        "Approved almost instantly for most eligible countries",
      ],
      applicationLinks: [
        {
          text: "Republic of Turkey Electronic Visa Application System",
          url: "https://www.evisa.gov.tr/en/",
        },
      ],
      processingTime: "Usually processed instantly or within 24 hours",
      cost: {
        amount: 0,
        currency: "USD (fees vary by nationality, typically $20-$80 USD)",
      },
      alternativeOptions: ["r1", "r23"],
      applicableCountries: [
        "Australia",
        "Bahrain",
        "Belgium",
        "Canada",
        "China",
        "Croatia",
        "Cyprus",
        "Dominican Republic",
        "Indonesia",
        "Ireland",
        "Kuwait",
        "Malta",
        "Mexico",
        "Netherlands",
        "Norway",
        "Oman",
        "Poland",
        "Portugal",
        "Qatar",
        "Saudi Arabia",
        "South Africa",
        "Spain",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "and others depending on current policy",
      ],
    },

    r23: {
      id: "r23",
      title: "Sticker Visa from Turkish Embassy/Consulate",
      description: "Traditional visa application through Turkish diplomatic missions for nationalities not eligible for e-Visa or visa exemption.",
      requirements: [
        "Valid passport with at least 6 months validity beyond entry date",
        "Completed visa application form",
        "Recent passport-sized photos",
        "Proof of travel purpose (hotel reservation, invitation letter, etc.)",
        "Flight reservations",
        "Proof of sufficient funds for your stay",
        "Travel insurance (may be required)",
        "Application must be made at Turkish Embassy or Consulate",
        "May require in-person appearance",
      ],
      applicationLinks: [
        {
          text: "Turkish Ministry of Foreign Affairs Visa Information",
          url: "http://www.mfa.gov.tr/visa-information-for-foreigners.en.mfa",
        },
      ],
      processingTime: "3-15 business days (may vary by country and visa type)",
      cost: {
        amount: 0,
        currency: "USD (fees vary by nationality and visa type)",
      },
      alternativeOptions: ["r22", "r24"],
      applicableCountries: [
        "Afghanistan",
        "Algeria",
        "Bangladesh",
        "Egypt",
        "India",
        "Iran",
        "Iraq",
        "Jordan",
        "Kenya",
        "Nigeria",
        "Pakistan",
        "Philippines",
        "Sudan",
        "and others not eligible for e-Visa or visa exemption",
      ],
    },

    r24: {
      id: "r24",
      title: "Turkish Visa Eligibility Check",
      description: "Information on how to determine visa requirements based on your citizenship.",
      requirements: [
        "Check the Republic of Turkey Ministry of Foreign Affairs website",
        "OR use the e-Visa website to check eligibility for electronic visa",
        "Requirements depend on:",
        "• Your citizenship",
        "• Purpose of visit",
        "• Length of stay",
        "• Current diplomatic relations",
        "If in doubt, contact nearest Turkish Embassy or Consulate",
      ],
      applicationLinks: [
        {
          text: "Turkish Ministry of Foreign Affairs Visa Information",
          url: "http://www.mfa.gov.tr/visa-information-for-foreigners.en.mfa",
        },
        {
          text: "e-Visa Eligibility Check",
          url: "https://www.evisa.gov.tr/en/apply/",
        },
      ],
      processingTime: "Immediate (for eligibility check only)",
      cost: {
        amount: 0,
        currency: "USD",
      },
      alternativeOptions: ["r1", "r22", "r23"],
      applicableCountries: ["All countries"],
    },
  },

  metadata: {
    version: "1.0.0",
    lastUpdated: "2025-03-20",
    author: "Emma",
    countries: ["Turkey"],
  },
};